version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://35.181.200.114:8000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - EMAIL_ID=havenbook564@gmail.com
      - EMAIL_PASSWORD=edufbztgatkqhaao
      - PORT=8000
      - DATABASE_URL=mongodb://database:27017/bookstore
      - JWT_KEY=JHsuYB12351SnmkKS@!#$#@
      - BASE_URL=http://35.181.200.114:8000/
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - ./mongo_data:/data/db
