version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://13.39.1.158:8000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - EMAIL_ID=havenbook564@gmail.com
      - EMAIL_PASSWORD=edufbztgatkqhaao
      - PORT=8000
      - DATABASE_URL=mongodb://database:27017/bookstore
      - JWT_KEY=My_secret_key8228
      - BASE_URL=http://13.39.1.158:8000/
      - AWS_S3_BUCKET_NAME=sudo-venom-bucket
      - AWS_S3_REGION=eu-west-3
      - WS_SECRET_ACCESS_KEY=RlU3Ir4KrhzDK9A4taYoEf+HrdZTbrTB/HSpR/Kr
      - AWS_ACCESS_KEY_ID=AKIARBUZNPTUIGFKOLTX
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - ./mongo_data:/data/db
